baseURL= "https://adriash.github.io"
languageCode= "es-es" 
title= "Mi portafolio" 
theme= "hugo-developer-portfolio"

[params.plugins]
  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"
  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"

[menu]
  [[menu.main]]
  name = "About"
  URL = "about"
  [[menu.main]]
  name = "Contact"
  URL = "contact"

[params]
home = "Home" # What you want the homepage to show up as in the menu bar
# Meta data
description = "Esta es una web dedicada a mi presentación, un alumno de grado superior de Desarrollo Web"
author = "Saz Adrián"


  [params.contact]
  formAction = "https://formspree.io/<Insert code>" # Add your formspree URL here to get emails

  # This contains the contact information for the footer
  [params.footer]
  email = "adriansazna@gmail.com"
  address = "Zaragoza, ES"
  googlemaps = "https://goo.gl/maps/3dvewu32ajiF4aKb8"

  